Welcome to the CRUX 3.5 installation media!

Press <Enter> to boot using the default 'CRUX' image
or use one of the others in the following list:

Available images:

  CRUX        - Install CRUX
  fb1280      - 1280x1024 framebuffer console
  fb1024      - 1024x768 framebuffer console
  fb800       - 800x600 framebuffer console
  fb640       - 640x480 framebuffer console
  memtest86+, - Test your system's RAM
  memtest86
  hdt         - Run the Hardware Detection Tool (HDT)

Press F3 to see IDE/SATA/USB/SCSI/FireWire options
Press F4 to see miscellaneous boot options (acpi, etc.)
Press F5 to see rescue options

