
Rescue options:

  (Note: separate with spaces when specifying multiple options)

  root=/dev/XXX  This option specifies an alternate root device for the boot
                 sequence to use rather than using the temporary root of the
                 CRUX install media. It can be used to boot a
                 previously-installed system with a kernel misconfiguration,
                 for example.

                 Example: "CRUX root=/dev/sda4"
                  (use /dev/sda4 as the root filesystem)

